server:
  port: 3344
spring:
  application:
    name: cloud-center-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:lyj0914/springcloud-config.git #GitHub上面的仓库名字
          #搜索目录
          search-paths:
            -springcloud-config
      #读取分支
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

